"""deleted some user columns

Revision ID: 640edad2d8c7
Revises: 92dddbf58219
Create Date: 2025-05-29 11:39:14.579629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640edad2d8c7'
down_revision: Union[str, None] = '92dddbf58219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
