"""add new columns

Revision ID: f9147083e6b4
Revises: 2b9bfd7ff9ef
Create Date: 2025-05-27 16:43:03.126330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9147083e6b4'
down_revision: Union[str, None] = '2b9bfd7ff9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'NOT_STARTED', name='status'), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
