version: '3.8'

services:

  backend:
    build:
      context: ./backend_server
    ports:
      - "5000:5000"
    
  frontend:
    build:
      context: ./frontend_server
    ports:
      - "8000:80" 